steps:
  - name: gcr.io/cloud-builders/docker
    args: 
        - build
        - '--no-cache'
        - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
        - .
        - '-f' 
        - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
        - run
        - deploy
        - update
        - $_SERVICE_NAME
        - '--image'
        - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
        - '--region'
        - '$_DEPLOY_REGION'
    entrypoint: gcloud
    id: Deploy
timeout: 1200s
images: 
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'   